### ISSUE TITLE
Unable to find autoload.php file

### ISSUE THREAD

**Issue by akanshgulati** [jayzeng/virustotal_apiwrapper#11]
I am not that use to composer. I want to get the autoload.php file as I am not able to find it in the repo. Moreover, is this Exception folder necessary because I have not seen any exception demo explaining how to use it.

**Comment by jayzeng** [comment]
Looks like you figured it out, which is good. You don't have to use composer, you can setup autoload in the way you like (which is what composer does behind the scene). 

Exceptions are indeed needed, you will get rate limit exception if you key exceeds virus total limit or api exception if you api key is invalid. I may or may not have covered all scenarios, let me know if you hit any road blocks. And thanks for pointing out that my examples didn't explain how to deal with exceptions, will update them later today.

**Comment by akanshgulati** [comment]
@jayzeng Yeah, I gave a look to composer and figured it out. I added many directories under Vendors. Anyways, your wrapper is far well documented as compare to others. Waiting for more updations.
