### ISSUE TITLE
Fatal error: Class 'VirusTotal\Url' not found in [...]/verify_urls.php on line 28

### ISSUE THREAD

**Issue by dzarezenko** [jayzeng/virustotal_apiwrapper#14]
Hi,

I have cloned your package with composer into my project but looks like Url class not found. I have other composer packages that works in the proper way, so strange for me.

My code is:

```
require_once("../vendor/autoload.php");

$file = new VirusTotal\Url("........");
$resp = $file->scan("........");

var_dump($resp);
exit();
```

**Comment by jayzeng** [comment]
@dzarezenko sounds like an issue in how you set up composer, can you post your composer.json and bit more relevant code? It is hard to tell what's problems are without more details.

**Comment by dzarezenko** [comment]
@jayzeng  I have default installation of composer and my composer.json for my project the next:

```
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "asymptix/framework",
                "version": "dev-master",
                "source": {
                    "type": "svn",
                    "url": "https://github.com/Asymptix/Framework",
                    "reference": "trunk/framework"
                },
                "require": {
                    "php": ">=5.4.0"
                },
                "autoload": {
                    "psr-4": {
                        "Asymptix\\": ""
                    }
                }
            }
        }
    ],
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "asymptix/framework": ">=2.0.0",
        "jayzeng/virustotalapi": "dev-master"
    }
}
```

**Comment by jayzeng** [comment]
@dzarezenko sorry for the delay, I am guessing it is because I didn't push the latest to composer. I just released a new build, can you run composer update to pull the latest again? 

Also you are using psr-4, I am not sure whether it introduces any breaking changes.

**Comment by dzarezenko** [comment]
@jayzeng  Thanks! Works now as a charm. What have you changed?

**Comment by jayzeng** [comment]
Ha, glad to hear that @dzarezenko, I pushed the latest code to packagist. My guess is the previous release didn't contain my recent refactoring changes. 

I am going to close this issue, feel free to re-open if you run into something else. Enjoy :)
