### ISSUE TITLE
Update requirements to use guzzlehttp/guzzle instead of guzzle/guzzle 

### ISSUE THREAD

**Issue by jmdevince** [jayzeng/virustotal_apiwrapper#15]
https://github.com/jayzeng/virustotal_apiwrapper/blob/master/composer.json#L17

Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by jayzeng** [comment]
Didn't know about the update, will take a look at it.

**Comment by jayzeng** [comment]
Thanks @mbarany for taking care of this, I will cut a new build today.

**Comment by jayzeng** [comment]
https://packagist.org/packages/jayzeng/virustotalapi#0.1.6 is now available.

**Comment by jmdevince** [comment]
Aesome, Thank you!
