### ISSUE TITLE
database needed?

### ISSUE THREAD

**Issue by voltan** [jayzeng/virustotal_apiwrapper#17]
Hello 
on virustotal website I see some request answered after some hours , how we can handel it ? any database needed ? 

do you have any method on your script for it?

thanks

**Comment by jayzeng** [comment]
@voltan sorry I don't follow your question, are you saying the requests take potentially a long time to process and you are looking for ways to pull the results?

**Comment by voltan** [comment]
Yes

**Comment by jayzeng** [comment]
There are many different ways to go around it, just to name a few:
- long polling
- cron job to refresh periodically (which you will need to maintain the url & result state and thus require some sort of persistent storage like db or redis)
- wait & retry by increasing the wait time exponentially (back off algorithm) 

This library is meant to simplify accessing virus total's api, these requirement goes beyond the design goal and you should implement it on your side.
