### ISSUE TITLE
Api is broken because of guzzle

### ISSUE THREAD

**Issue by jokaorgua** [jayzeng/virustotal_apiwrapper#18]
Guzzle 6.2.0 is using form_params to send post data. And has no response->json method. Add this code to makePostRequest `if(empty($params['form_params']))
$params['form_params'] = $params`

And all response->json rewrite to `return json_decode($data->getBody()->getContents(),true);`

**Comment by jayzeng** [comment]
@jokaorgua thanks for the heads-up, looks like guzzle did some crazy rewrite and the recent changes breaks the code. I will fix it soon.

**Comment by Demonslay335** [comment]
I can confirm that #19 fixes to issue for my website.

**Comment by jayzeng** [comment]
@jokaorgua @Demonslay335 sorry for the delay, just released a version to composer. Please give it a shot.

**Comment by jayzeng** [comment]
https://github.com/jayzeng/virustotal_apiwrapper/pull/20 was the changes
